### ISSUE TITLE
Pass custom parameters to start-storybook

### ISSUE THREAD

**Issue by VickyKoblinski** [joshbolduc/vscode-story-explorer#121]
I'm enjoying this plugin! Unfortunately it doesn't work for me because our project setup. Specifically our start script calls `start-storybook -p 6006 -s public`. Being able to pass in these parameters is all I need.

**Comment by joshbolduc** [comment]
Glad you like the extension!

It's not obvious, but you can set the port using environment variables. Something like:

```jsonc
// .vscode/settings.json
{
  "storyExplorer.server.internal.environmentVariables": {
    "SBCONFIG_PORT": "6006"
  }
}
```

It _should_ also be possible to [set a static directory using `SBCONFIG_STATIC_DIR`](https://github.com/storybookjs/storybook/blob/30467981c7103f98b6943cc660440c7e7e54fedb/lib/core-server/src/cli/dev.ts#L74) but from my testing, it looks like that env var might be broken, at least in recent versions of Storybook. Even if it did work, it would be nice to have a more convenient way to configure settings that are only available via the CLI.

**Comment by VickyKoblinski** [comment]
Thank you! That worked beautifully and now Storybook 6.4 wants the staticDirs defined in the `main.js` which resolved the other issue I had as well. https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated---static-dir-cli-flag

Now the extension is totally working! Thank you for pointing me in the right direction.
