### ISSUE TITLE
Preview does not load

### ISSUE THREAD

**Issue by IanVS** [joshbolduc/vscode-story-explorer#461]
I'm excited to try out this extension, but when I try opening a preview, I only see a "Loading..." message forever.  I enabled debug logs, and all I see is:

```
[debug] Webview host received message [object Object]
```

The storybook server starts correctly in the terminal pane, and if I open the url for the storybook in a browser, it loads up just fine.

Here's a repository that demonstrates this (note that it's a branch, it's also a reproduction for a separate issue). https://github.com/IanVS/storybook-mdx2-reproduction/tree/fix-mdx2.

I tried both the webpack and vite builders, as well as disabling storyStoreV7.  It also happens in a different project of mine using mdx1 and react 17.

**Comment by IanVS** [comment]
With the new version, I see the following output:

```
[debug] Scanning process 28844 for opened port
[debug] Webview host received message {"type":0}
```

Are you able to reproduce the issue with the provided repo?

**Comment by joshbolduc** [comment]
No, unfortunately I wasn't able to repro this one either. (Was hoping we'd find something in common with #460, but they do seem unrelated.)

From the logs it looks like the extension is failing to detect the opened port. Could you share the output of

```shell
lsof -aPi -Fn -p 28844
```

(where `28844` is the process ID mentioned in the log), and the port that the dev server output indicates it's listening on?

**Comment by IanVS** [comment]
I'm not sure what changed, but I tested this back out today and my stories are previewing correctly!  Thanks for your work on this extension, I'm excited to start using it.
