### ISSUE TITLE
No stories were found.

### ISSUE THREAD

**Issue by joelstransky** [joshbolduc/vscode-story-explorer#99]
Using storybook 6.3.7 which is completely functional. Added Story Explorer addon and it can't find any stories in the panel no matter how many path variations I try. The `Open Storybook Config` and `Open Storybook in browser` both work (if I set storyExplorer.server.internal.enabled to false and launch manually). What is this extension doing different from storybook's story locator?
I have multiple sub-storybook configurations and the issue persists no matter which one I point storyExplorer.storybookConfigDir to.

**Comment by joshbolduc** [comment]
That seems fine to me. Replicating your setup as best I can, I see the story show up as expected:

![image](https://user-images.githubusercontent.com/25474557/139505513-7accc319-e6ec-41af-af0e-2f902b5a0536.png)

Wonder if maybe there's something more going on in your `main.js` that can't be read for some reason. That file _is_ actually evaluated (i.e., using `require`), so it's conceivable something could not be working there when the extension tries to read it that works when it's read by storybook.

**Comment by joshbolduc** [comment]
I've added a couple things to make this type of thing easier to diagnose. There's now a `storyExplorer.logLevel` setting that you can use to enable more verbose logging via the output panel. I've also added specific handling for when we run into a problem parsing `main.js` so the message in the stories panel should be more direct (if that is, in fact, the cause).

If you're still having this problem, feel free to bump up the log level (e.g., `warn` or above will capture any issues parsing `main.js`) and post the output here.
